// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           20
// Async Callback:                       1
// Total number of exported functions:  23

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    identity_registry
    (
        init => init
        upgrade => upgrade
        issue_token => issue_token
        register_agent => register_agent
        update_agent => update_agent
        set_metadata => set_metadata
        set_service_configs => set_service_configs_endpoint
        remove_metadata => remove_metadata
        remove_service_configs => remove_service_configs
        get_agent_token_id => agent_token_id
        get_agent_id => agents
        get_agent_details => agent_details
        get_agent_metadata => agent_metadata
        get_agent_service => agent_service_config
        get_agent => get_agent
        get_agents => get_agents
        get_agent_count => get_agent_count
        get_agent_owner => get_agent_owner
        get_metadata => get_metadata
        get_agent_metadata_page => get_agent_metadata_page
        get_agent_service_config => get_agent_service_config
        get_agent_service_configs_page => get_agent_service_configs_page
    )
}

multiversx_sc_wasm_adapter::async_callback! { identity_registry }
