// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct IdentityRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for IdentityRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = IdentityRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        IdentityRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct IdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> IdentityRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> IdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> IdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn issue_token<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_display_name: Arg0,
        token_ticker: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("issue_token")
            .argument(&token_display_name)
            .argument(&token_ticker)
            .original_result()
    }

    /// Register a new agent with name, URI, public key, optional metadata, and optional service configs. 
    pub fn register_agent<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<MultiValueEncoded<Env::Api, common::structs::MetadataEntry<Env::Api>>>,
        Arg4: ProxyArg<MultiValueEncoded<Env::Api, common::structs::ServiceConfigInput<Env::Api>>>,
    >(
        self,
        name: Arg0,
        uri: Arg1,
        public_key: Arg2,
        metadata: Arg3,
        services: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("register_agent")
            .argument(&name)
            .argument(&uri)
            .argument(&public_key)
            .argument(&metadata)
            .argument(&services)
            .original_result()
    }

    /// Update an agent's URI and/or public_key. Requires sending the agent NFT. 
    pub fn update_agent<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<OptionalValue<MultiValueEncoded<Env::Api, common::structs::MetadataEntry<Env::Api>>>>,
        Arg4: ProxyArg<OptionalValue<MultiValueEncoded<Env::Api, common::structs::ServiceConfigInput<Env::Api>>>>,
    >(
        self,
        new_name: Arg0,
        new_uri: Arg1,
        new_public_key: Arg2,
        metadata: Arg3,
        services: Arg4,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("update_agent")
            .argument(&new_name)
            .argument(&new_uri)
            .argument(&new_public_key)
            .argument(&metadata)
            .argument(&services)
            .original_result()
    }

    /// Set or update metadata entries for an agent. O(1) per entry via MapMapper. 
    pub fn set_metadata<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<MultiValueEncoded<Env::Api, common::structs::MetadataEntry<Env::Api>>>,
    >(
        self,
        nonce: Arg0,
        entries: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("set_metadata")
            .argument(&nonce)
            .argument(&entries)
            .original_result()
    }

    /// Set or update service configurations for an agent. 
    pub fn set_service_configs_endpoint<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<MultiValueEncoded<Env::Api, common::structs::ServiceConfigInput<Env::Api>>>,
    >(
        self,
        nonce: Arg0,
        configs: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("set_service_configs")
            .argument(&nonce)
            .argument(&configs)
            .original_result()
    }

    /// Remove metadata entries by key. 
    pub fn remove_metadata<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<MultiValueEncoded<Env::Api, ManagedBuffer<Env::Api>>>,
    >(
        self,
        nonce: Arg0,
        keys: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("remove_metadata")
            .argument(&nonce)
            .argument(&keys)
            .original_result()
    }

    /// Remove service configurations by service ID. 
    pub fn remove_service_configs<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<MultiValueEncoded<Env::Api, u32>>,
    >(
        self,
        nonce: Arg0,
        service_ids: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("remove_service_configs")
            .argument(&nonce)
            .argument(&service_ids)
            .original_result()
    }

    pub fn agent_token_id(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, EsdtTokenIdentifier<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_token_id")
            .original_result()
    }

    pub fn agents(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, MultiValue2<u64, ManagedAddress<Env::Api>>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_id")
            .original_result()
    }

    pub fn agent_details<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, common::structs::AgentDetails<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_details")
            .argument(&nonce)
            .original_result()
    }

    pub fn agent_metadata<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, MultiValue2<ManagedBuffer<Env::Api>, ManagedBuffer<Env::Api>>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_metadata")
            .argument(&nonce)
            .original_result()
    }

    pub fn agent_service_config<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, MultiValue2<u32, Payment<Env::Api>>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_service")
            .argument(&nonce)
            .original_result()
    }

    pub fn get_agent<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, common::structs::AgentDetails<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent")
            .argument(&nonce)
            .original_result()
    }

    /// Paginated list of agents. `from` = start index, `size` = max items (capped at 100).
    pub fn get_agents<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        from: Arg0,
        size: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, common::structs::AgentListEntry<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agents")
            .argument(&from)
            .argument(&size)
            .original_result()
    }

    pub fn get_agent_count(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_count")
            .original_result()
    }

    pub fn get_agent_owner<
        Arg0: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_owner")
            .argument(&nonce)
            .original_result()
    }

    pub fn get_metadata<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        nonce: Arg0,
        key: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<ManagedBuffer<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_metadata")
            .argument(&nonce)
            .argument(&key)
            .original_result()
    }

    /// Paginated metadata entries for an agent.
    pub fn get_agent_metadata_page<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
        from: Arg1,
        size: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, common::structs::MetadataEntry<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_metadata_page")
            .argument(&nonce)
            .argument(&from)
            .argument(&size)
            .original_result()
    }

    pub fn get_agent_service_config<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u32>,
    >(
        self,
        nonce: Arg0,
        service_id: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<EgldOrEsdtTokenPayment<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_service_config")
            .argument(&nonce)
            .argument(&service_id)
            .original_result()
    }

    /// Paginated service configs for an agent.
    pub fn get_agent_service_configs_page<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<u64>,
    >(
        self,
        nonce: Arg0,
        from: Arg1,
        size: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, common::structs::ServiceConfigEntry<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_service_configs_page")
            .argument(&nonce)
            .argument(&from)
            .argument(&size)
            .original_result()
    }
}
