// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct ReputationRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for ReputationRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = ReputationRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        ReputationRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct ReputationRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> ReputationRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        validation_contract_address: Arg0,
        identity_contract_address: Arg1,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&validation_contract_address)
            .argument(&identity_contract_address)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ReputationRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ReputationRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    /// Simple feedback for a job. Caller must be the employer who created the job. 
    /// Computes a cumulative moving average on-chain. 
    pub fn give_feedback_simple<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        job_id: Arg0,
        agent_nonce: Arg1,
        rating: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("giveFeedbackSimple")
            .argument(&job_id)
            .argument(&agent_nonce)
            .argument(&rating)
            .original_result()
    }

    /// ERC-8004: Anyone can give feedback (except the agent owner). 
    /// Stores raw signals — no on-chain scoring. Off-chain aggregation expected. 
    pub fn give_feedback<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<i64>,
        Arg2: ProxyArg<u8>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg5: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg6: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg7: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        agent_nonce: Arg0,
        value: Arg1,
        value_decimals: Arg2,
        tag1: Arg3,
        tag2: Arg4,
        endpoint: Arg5,
        feedback_uri: Arg6,
        feedback_hash: Arg7,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("giveFeedback")
            .argument(&agent_nonce)
            .argument(&value)
            .argument(&value_decimals)
            .argument(&tag1)
            .argument(&tag2)
            .argument(&endpoint)
            .argument(&feedback_uri)
            .argument(&feedback_hash)
            .original_result()
    }

    /// ERC-8004: Only the original feedback author can revoke their feedback. 
    pub fn revoke_feedback<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        agent_nonce: Arg0,
        feedback_index: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("revokeFeedback")
            .argument(&agent_nonce)
            .argument(&feedback_index)
            .original_result()
    }

    pub fn read_feedback<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
        Arg2: ProxyArg<u64>,
    >(
        self,
        agent_nonce: Arg0,
        client: Arg1,
        feedback_index: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, FeedbackData<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("readFeedback")
            .argument(&agent_nonce)
            .argument(&client)
            .argument(&feedback_index)
            .original_result()
    }

    /// ERC-8004: Anyone can append a response to feedback (e.g., agent showing refund, 
    /// data aggregator tagging feedback as spam). 
    pub fn append_response<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
        response_uri: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("append_response")
            .argument(&job_id)
            .argument(&response_uri)
            .original_result()
    }

    pub fn reputation_score<
        Arg0: ProxyArg<u64>,
    >(
        self,
        agent_nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_reputation_score")
            .argument(&agent_nonce)
            .original_result()
    }

    pub fn total_jobs<
        Arg0: ProxyArg<u64>,
    >(
        self,
        agent_nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_total_jobs")
            .argument(&agent_nonce)
            .original_result()
    }

    pub fn validation_contract_address(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_validation_contract_address")
            .original_result()
    }

    pub fn identity_contract_address(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_identity_contract_address")
            .original_result()
    }

    pub fn has_given_feedback<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("has_given_feedback")
            .argument(&job_id)
            .original_result()
    }

    pub fn agent_response<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedBuffer<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_response")
            .argument(&job_id)
            .original_result()
    }

    pub fn last_feedback_index<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        agent_nonce: Arg0,
        client: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getLastIndex")
            .argument(&agent_nonce)
            .argument(&client)
            .original_result()
    }

    pub fn feedback_clients<
        Arg0: ProxyArg<u64>,
    >(
        self,
        agent_nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, ManagedAddress<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getClients")
            .argument(&agent_nonce)
            .original_result()
    }

    /// Paginated list of client addresses who gave feedback to an agent.
    pub fn get_feedback_clients_page<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<u64>,
    >(
        self,
        agent_nonce: Arg0,
        from: Arg1,
        size: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, ManagedAddress<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getFeedbackClientsPage")
            .argument(&agent_nonce)
            .argument(&from)
            .argument(&size)
            .original_result()
    }

    pub fn set_identity_contract_address<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("set_identity_contract_address")
            .argument(&address)
            .original_result()
    }

    pub fn set_validation_contract_address<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("set_validation_contract_address")
            .argument(&address)
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, PartialEq, Debug)]
pub struct FeedbackData<Api>
where
    Api: ManagedTypeApi,
{
    pub value: i64,
    pub value_decimals: u8,
    pub tag1: ManagedBuffer<Api>,
    pub tag2: ManagedBuffer<Api>,
    pub is_revoked: bool,
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode)]
pub struct NewFeedbackEventData<Api>
where
    Api: ManagedTypeApi,
{
    pub feedback_index: u64,
    pub value: i64,
    pub value_decimals: u8,
    pub tag1: ManagedBuffer<Api>,
    pub tag2: ManagedBuffer<Api>,
    pub endpoint: ManagedBuffer<Api>,
    pub feedback_uri: ManagedBuffer<Api>,
    pub feedback_hash: ManagedBuffer<Api>,
}
