// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct ValidationRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for ValidationRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = ValidationRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        ValidationRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct ValidationRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> ValidationRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        identity_registry_address: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&identity_registry_address)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ValidationRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ValidationRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn init_job<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<OptionalValue<u32>>,
    >(
        self,
        job_id: Arg0,
        agent_nonce: Arg1,
        service_id: Arg2,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("init_job")
            .argument(&job_id)
            .argument(&agent_nonce)
            .argument(&service_id)
            .original_result()
    }

    pub fn submit_proof<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
        proof: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("submit_proof")
            .argument(&job_id)
            .argument(&proof)
            .original_result()
    }

    /// NFT-holder variant: proves ownership by sending the agent NFT. 
    /// The contract verifies token ID + nonce, executes proof, and returns the NFT. 
    pub fn submit_proof_with_nft<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
        proof: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("submit_proof_with_nft")
            .argument(&job_id)
            .argument(&proof)
            .original_result()
    }

    /// ERC-8004: Agent requests validation from a specific validator. 
    /// MUST be called by the owner of the agent (agentId). 
    pub fn validation_request<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
        validator_address: Arg1,
        request_uri: Arg2,
        request_hash: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("validation_request")
            .argument(&job_id)
            .argument(&validator_address)
            .argument(&request_uri)
            .argument(&request_hash)
            .original_result()
    }

    /// ERC-8004: Validator responds with a result (0-100). 
    /// MUST be called by the validatorAddress from the original request. 
    /// Can be called multiple times for progressive validation. 
    pub fn validation_response<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u8>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        request_hash: Arg0,
        response: Arg1,
        _response_uri: Arg2,
        response_hash: Arg3,
        tag: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("validation_response")
            .argument(&request_hash)
            .argument(&response)
            .argument(&_response_uri)
            .argument(&response_hash)
            .argument(&tag)
            .original_result()
    }

    pub fn clean_old_jobs<
        Arg0: ProxyArg<MultiValueEncoded<Env::Api, ManagedBuffer<Env::Api>>>,
    >(
        self,
        job_ids: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("clean_old_jobs")
            .argument(&job_ids)
            .original_result()
    }

    pub fn is_job_verified<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("is_job_verified")
            .argument(&job_id)
            .original_result()
    }

    pub fn get_job_data<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        job_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<common::structs::JobData<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_job_data")
            .argument(&job_id)
            .original_result()
    }

    /// ERC-8004: Returns validation status for a request hash. 
    pub fn get_validation_status<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        request_hash: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<common::structs::ValidationRequestData<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_validation_status")
            .argument(&request_hash)
            .original_result()
    }

    /// ERC-8004: Returns all validation request hashes for an agent. 
    pub fn get_agent_validations<
        Arg0: ProxyArg<u64>,
    >(
        self,
        agent_nonce: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, ManagedBuffer<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_validations")
            .argument(&agent_nonce)
            .original_result()
    }

    /// Paginated validation hashes for an agent. `from` = start index, `size` = max items (capped at 100).
    pub fn get_agent_validations_page<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<u64>,
    >(
        self,
        agent_nonce: Arg0,
        from: Arg1,
        size: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, ManagedBuffer<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_agent_validations_page")
            .argument(&agent_nonce)
            .argument(&from)
            .argument(&size)
            .original_result()
    }

    pub fn set_identity_registry_address<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("set_identity_registry_address")
            .argument(&address)
            .original_result()
    }
}
