// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           16
// Async Callback (empty):               1
// Total number of exported functions:  19

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    reputation_registry
    (
        init => init
        upgrade => upgrade
        giveFeedbackSimple => give_feedback_simple
        giveFeedback => give_feedback
        revokeFeedback => revoke_feedback
        readFeedback => read_feedback
        append_response => append_response
        get_reputation_score => reputation_score
        get_total_jobs => total_jobs
        get_validation_contract_address => validation_contract_address
        get_identity_contract_address => identity_contract_address
        has_given_feedback => has_given_feedback
        get_agent_response => agent_response
        getLastIndex => last_feedback_index
        getClients => feedback_clients
        getFeedbackClientsPage => get_feedback_clients_page
        set_identity_contract_address => set_identity_contract_address
        set_validation_contract_address => set_validation_contract_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
